### ISSUE TITLE
forms - sex up the admin

### ISSUE THREAD

**Issue by bioshazard** [eflip/Forms#1]

**Comment by wightmike** [comment]
Forms is not currently a live app.

Should we keep this issue open, or close it and open a new issue when forms comes back into relevance?

**Comment by bioshazard** [comment]
I recommend you open a new issue and mention that is it blocking #1

**Comment by wightmike** [comment]
I'm going to close this issue as Forms is not a live or priority app at this time. We can open a new one when Forms is relevant.

**Comment by bioshazard** [comment]
I recommend you open a new issue and mention that is it blocking #1

**Comment by wightmike** [comment]
I'd rather just close it and come back to forms later. If you have any objections I would prefer to sort them in a meeting at this point.
